[package]
name = "memory_canister"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.0"
ic-cdk = "0.15.1"
ic-cdk-macros = "0.6.8"
canbench-rs = {version = "0.1.4", optional = true}
ic0 = "0.23.0"

[profile.release]
lto = true
opt-level = 3